project_id = "szvskyxczgvfcbucmjjk"

[functions.asaas]
verify_jwt = false

[functions.create-collaborator-user]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false
